### ISSUE TITLE
open bor

### ISSUE THREAD

**Issue by itchyd** [jimgraygit/Onion#147] opened 2022-04-23 10:23 UTC
There doesn't seem to be a way to get Open BOR to recognize game paks?   Thanks for all your hard work!

**Comment by dwmccoy** [comment] 2022-04-23 14:21
Duplicate of #124.

**Comment by Sichroteph** [comment] 2022-05-30 07:50
I believe it is fixed now. Thanks for your feedback.

**Closed by Sichroteph** 2022-05-30 07:50 UTC
