### ISSUE TITLE
Imgs folder is visible inside Pico-8 game list

### ISSUE THREAD

**Issue by S1CKSPEED** [jimgraygit/Onion#279] opened 2022-05-25 14:49 UTC
The Imgs Folder is visible inside Pico-8 game list. This is not the case with any other platform (as far as I have tested)
![PXL_20220525_144812641](https://user-images.githubusercontent.com/96639089/170291288-95553842-3d14-4a76-be22-1143158a5046.jpg)
.

**Comment by Olywa** [comment] 2022-05-25 15:00
This is not a bug as such but more an unfortunate side effect of PICO8 using an already known and in use file format for their games (.png). OnionOS thinks that there are games in the Imgs folder because the files there have the same extension. 

The only workaround would be to edit your game files to remove the .png (i.e. 'gamenam.p8') and then to edit the EMU/PICO/config.json file manually to remove png from the "extlist":"p8|png" line. The folder should then no longer be visible. 

--
If this resolves your issue, please consider changing the status to CLOSED as it saves the developer time in managing issues.
Thank you.

**Closed** 2022-05-25 15:02 UTC

**Comment by S1CKSPEED** [comment] 2022-05-25 15:21
Absolutely right! My foult as it has a lot of sense. Apologize to spend your time and thank you for your fast comment @Olywa ! I will continue enjoying this awesome machine and custo OS.
