### ISSUE TITLE
PS1 Tomba 2 sound slowdown

### ISSUE THREAD

**Issue by CloudTF25** [jimgraygit/Onion#362] opened 2022-06-11 16:10 UTC
So when you play the first level and allow the music to change to a different track after a minute. The new track will stutter and slowdown
https://github.com/notaz/pcsx_rearmed/issues/102 < supposedly in this link, it has already been fixed in retroarch and it's the newest version? Could you possibly rebuild or update the ps1 core for the miyoo mini? I don't mind testing it!

ps: i'm using thepsxonpsp660.bin and a clean dump of the game in CHD format. 

video below shows the issue in action

https://user-images.githubusercontent.com/67326185/173195693-81646256-5dde-442e-8ea5-6b5e4aa4b50b.mp4

**Comment by CloudTF25** [comment] 2022-06-11 16:10
Any fixes or solutions to this will be greatly appreciated!

**Comment by Olywa** [comment] 2022-06-11 22:07
Hi there, my take on this one. The issue is not with retroarch as such but the specific core (PCSX Rearmed). Following your link to the core issue reporting, the issues (#102 and #122) are both still 'open' suggesting it's not been resolved. There was some overlap with issue #526 which was resolved and closed but that thread discussed only other games (Xenogears , CTR, FF8, etc.). The fact that the earlier issues have not been closed suggests the fix (CD timings) never resolved the issue in this particular game (and at least nobody in those threads has said as much). I may have missed something so please feel free to correct me.    

With each Onion release eggs is typically providing a new RA build with the very latest compiled cores so the one in Onion today should already be fairly recent. 

For the Onion devs, I'm not sure anything can be done to resolve this for you, as to me, it remains an issue with the core and core specific issues are a bit beyond the Onion devs remit :(

**Comment by CloudTF25** [comment] 2022-06-11 22:24
Ah damn :( is there any chance another PS1 emulator could be ported over? Or check if the current PS1 emulator is at update: r23

Thank you

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Olywa** [comment] 2022-06-12 00:48
I honestly don't think eggs will be up for the extra effort to try to resolve one specific game issue, he already gives up a lot of his spare time for Onion. I will ask @Sichroteph to comment on that. I'm also not sure which revision (i.e. r23) was used or how to tell. 

You could try testing one of the nightly's (by definition the very latest core release) from:
https://classicmodscloud.com/classic_libretro/nightly/classic_armv7_a7/2022-06-12/so/

Download the pcsx_rearmed_libretro.so and replace the one in your RetroArch\ .retroarch\cores\ folder
**I would suggest to first rename your existing core to pcsx_rearmed_libretro.so.OLD so you can easily revert back.**

The thing is, eggs is not just using off the shelf cores but is already tweaking and removing unnecessary features to improve performance and comiling his own so you may find the latest core actually performs worse on the (relatively low powered) Miyoo Mini.

**Comment by CloudTF25** [comment] 2022-06-12 01:26
> I honestly don't think eggs will be up for the extra effort to try to resolve one specific game issue, he already gives up a lot of his spare time for Onion. I will ask @Sichroteph to comment on that. I'm also not sure which revision (i.e. r23) was used or how to tell.
> 
> You could try testing one of the nightly's (by definition the very latest core release) from: https://classicmodscloud.com/classic_libretro/nightly/classic_armv7_a7/2022-06-12/so/
> 
> Download the pcsx_rearmed_libretro.so and replace the one in your RetroArch\ .retroarch\cores\ folder **I would suggest to first rename your existing core to 'pcsx_rearmed_libretro.so.OLD' so that you can easily revert back.**
> 
> The thing is, eggs is not always using off the shelf cores (at leas I think this is the case for PCSX) but is already tweaking and removing unnecessary features to improve performance and compiling his own so you may find the latest available core actually performs worse on the (relatively low powered) Miyoo Mini.

![Screenshot_20220612-022246](https://user-images.githubusercontent.com/67326185/173210290-63c5c6c0-7c85-4cc6-af83-2d0ae6c78903.jpg)

I only saw r23 because of the pcsx rearmed emulator GitHub readme lol. But I would be Incredibly thankful if you could forward this issue to @Sichroteph

Thank you for the link and I'll go ahead and try it out!

**Comment by CloudTF25** [comment] 2022-06-12 02:25
https://github.com/grumpycoders/pcsx-redux 
@Sichroteph 
@Olywa 
prehaps this could be a future replacement to the ps1 emu? I've read on the original emulator github's issues and it seems to be fixed in this version?

**Comment by Olywa** [comment] 2022-06-12 15:00
There would be a lot more work here than you might imagine to port, test, tweak, repeat. I'm not even convinced that the Mini is capable of running a 'ported pcsx-redux' as it looks like the hardware expectations would be much higher. 

The Onion developers are not in the habit of making ports, it's beyond the scope of the OnionOS project (which makes use of existing emulators and Retroarch cores).

**Comment by CloudTF25** [comment] 2022-06-12 17:24
Fair enough I understand that, it's sad to see it be a long standing issue tho :(. I wish the official Dev of the pscx rearmed emulator would try and fix it

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Olywa** [comment] 2022-06-13 02:56
Did you try the alternative core I linked, any luck with that?

Since this is not an issue with OnionOS as such but more with the core (and an enhancement request to look at replacing the default core) I would ask that you close the issue here and raise it in the discussions tab. It may also help you if you can garner support there for the enhancement.

**Comment by CloudTF25** [comment] 2022-06-13 03:03
Heya sorry I was busy mostly all day. But yeah I tried it and it didn't work. Should I raise a issue on the emulator's own GitHub? Or should I raise it somewhere else on here?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Olywa** [comment] 2022-06-13 19:02
The Onion team cannot solve longstanding issues with cores so there would be no benefit to raise that here. The issue has already been raised twice with the cores own dev team as discussed (102 and 122 on the cores own github) so I think raising it there again may be fruitless but you could at least add comments and endorsement to those existing issues.

For the enhancement request (to seek an improved emulator for PS1 in Onion), that can be raised in the discussion tab but I really the the options are limited and we are already very lucky to have PS1 emulation at all on such a low power device.

**Comment by CloudTF25** [comment] 2022-06-14 15:04
Rip well this is really unfortunate. Though this issue also happens on my raspberry pi 4 on the same core. So yeah :(

**Comment by Olywa** [comment] 2022-06-15 10:48
@CloudTF25 I see you've now moved this to [discussions](https://github.com/jimgraygit/Onion/discussions/375), could I ask you to set the issue status to closed please. Many thanks.

**Closed** 2022-06-15 11:07 UTC
