### ISSUE TITLE
No consoles after OnionOS 3.8.1 install

### ISSUE THREAD

**Issue by mvergaraq** [jimgraygit/Onion#150] opened 2022-04-24 04:51 UTC
Hi! i made a fresh install of OnionOS 3.8.1 on my Miyoo Mini v2, but after I picked the emulators I wanted and Onion installed them, the device doesn't show any emulator on the Consoles tab.

Also no emulators present on the Expert tab.

I'm using a brand microSD, which was formatted to fat32 prior to OnionOS install.
I also had the same issue before, when installing OnionOS 3.7, no consoles showing. I thought it was going to get fixed on this new release, but it didn't.

The device was showing games and consoles just fine with the stock microSD (and OS) it came with.

**Comment by Jimmy-Z** [comment] 2022-04-24 08:37
I've got exactly the same experience, with 3.7 and 3.8.1, forgot to sync I suppose?

Installer works after reboot though.

**Comment by 7zxkv** [comment] 2022-04-24 09:39
hi, 

just in case...are you sure you have the latest firmware (20220419): https://lemiyoo.cn/upgrade/675.html)?

_PS: note for "v2": the hardware is the same. only the battery changes (less practical by the way for a slightly higher power) and a very very slightly reduced screen volume. There is no need to make a difference here (it will add confusion the day a real v2 comes out), at best talking about a wave 2..._

**Comment by Sichroteph** [comment] 2022-04-24 13:30
Changing the firmware is actually not needed nor recommended.

**Comment by Sichroteph** [comment] 2022-04-24 13:33
I never had this issue so it is a bit difficult for me to reproduce it. If you have a method to do so that would be great. Did you picked apps also or just emulators ?

**Comment by Sichroteph** [comment] 2022-04-24 13:37
there is a sync at the end of the installation process

**Comment by Jimmy-Z** [comment] 2022-04-24 13:58
As for my case, 3.7 was on v1 with previous firmware (Jan?), with apps, 3.8.1 was today on v2 with current firmware, only emulators.

Both case I didn't format, just moved all stock files into a directory named "stock".

Both with the no brand 32GB card from miyoo.

**Comment by mvergaraq** [comment] 2022-04-24 14:48
Hey everyone I managed to get the consoles to show. Instead of installing the consoles when Onion is booting for the first time, install them via the Onion Installer app which is in the app tab, to me it worked that way.

**Comment by 7zxkv** [comment] 2022-04-24 15:43
> Changing the firmware is actually not needed nor recommended.

before it says "Compatible with all firmware versions." it was marked that it was necessary to update the firmware. at the time of my message....

**Comment by Sichroteph** [comment] 2022-04-25 07:49
> 

Sorry I must have say "not needed anymore"

**Comment by Sichroteph** [comment] 2022-04-25 07:51
A sync line has been added in the installer script that should fix it. (v3.8.2)
I will leave this ticket opened to be sure.

**Comment by citrovia** [comment] 2022-04-26 22:23
Is there a chance the full EMU folder containing all "games" files (configs, sms, launch and ic-SMS) is available somewhere? I upgraded to the latest OS (202204190828) and the EMU folder within the package I downloaded only contained MS, MD and PS EMU folders. Meanwhile, my Onion Installer does not contain any Consoles to be able to replace them.

**Comment by Sichroteph** [comment] 2022-04-27 07:46
Do you mean the stock OS has consoles that the Onion does not ?

**Comment by citrovia** [comment] 2022-04-27 13:36
Hey,
Thanks for the response. I followed the instructions from this video: https://www.youtube.com/watch?v=KDnuta3ZFGA

Which led me to download a package from this page: https://lemiyoo.cn/upgrade/675.html 

In both the update instructions as well as the video, they tell you to grab folders from the download zip and overwrite to the SD card once the firmware is updated. The unfortunate part is that after I overwrote the folders, I saw that the EMU folder only contained folders for MS, MD and PS which are the only emulators that appear in the GAMES menu on Onion. Previous EMU folders would have contained all of the various systems. Since I hadn't backed up my previous SD card (rookie move), I no longer have the remaining systems. 

My next move was to go to the Onion Installer option in App menu however no Consoles appear in the window in order to reinstall.

**Comment by DePingus** [comment] 2022-05-12 19:37
This just happened to me on a fresh install of 3.9.2 (v2 Miyoo Mini with firmware 202201082152). I was able to make all the consoles appear by going to App > The Onion Installer and going through the initial setup again.

**Comment by Sichroteph** [comment] 2022-05-30 07:50
Thanks for your feedbacks, closing now.

**Closed by Sichroteph** 2022-05-30 07:50 UTC

**Comment by AlexanderBeers** [comment] 2022-06-04 07:59
I had the same error after wiping my microSD and installing onion, but installing with the installer app didn't resolve it. A log said something like 'GBA/GBA_cache.db couldn't be opened' - apparently the respective folder and filename were in lowercase. I made them match the case and now my roms load properly!
