### ISSUE TITLE
Trouble resuming MAME Arcade games

### ISSUE THREAD

**Issue by dariusdan** [jimgraygit/Onion#377] opened 2022-06-14 00:14 UTC
I am having an issue where if I start a Mame game from the Arcade console, press the home button to access the home screen and go back to the game again, it sometimes loads the previous state with no sound, or with a different music playing, or even some weird annoying noise. Sometimes the game freezes entirely.

Additionally, if I turn the device on with Onion Launcher enabled, resume from an Arcade game and press the home button > start, it doesn't go back to the home screen at all. The screen just becomes black. I have to turn the device off, then on again, resume from a non-Mame game and finally I will be able to access the home screen normally.

I am using Mame 2003+ unmerged roms that I checked using romcenter and a dat file.

I tried some NeoGeo fbalpha compatible roms and the resume worked normally, but some of the games I want aren't CPS1-3 nor Neo Geo and I would prefer to only use one rom set on the device.

Edit: This issue is being discussed in here: https://github.com/jimgraygit/Onion/issues/142
I'm sorry to have it posted in a different topic.

**Comment by Olywa** [comment] 2022-06-14 02:04
Hi there, the other issue you mentioned was more related to Neo Geo (and the use of a very specific Bios file). Your issues appear to relate only to Mame it seems and this is a known issue that cannot be resolved by the Onion team. 

Mame200+ just does not play well with save states (on most if not all systems), it's an issue with the core unfortunately (the odd game will actually work OK but far more do not). Nothing can be done I'm afraid. We have to remember that Mame is emulating literally hundreds of different arcade machines vs. a home console core (which emulates one) so save state implementation becomes very complex.

You have two real options here:

1. Each time, upon re-entering a Mame game,  press Start+Select (for RA menu) and chose restart, this will resolve it the audio/glitching but obviously reset the game.

2. You can disable auto loading of save states (for Mame) in the RA menu if you prefer and 'save the core overrides' for it to stick so that each time you load a Mame games, it starts 'fresh' but at least without any issues. 

I do not recommend fiddling too much with other RA setting if unsure what you are doing as you may break emulation.

**Comment by dariusdan** [comment] 2022-06-14 02:12
> Hi there, the other issue you mentioned was more related to Neo Geo (and the use of a very specific Bios file). Your issues appear to relate only to Mame it seems and this is a known issue that cannot be resolved by the Onion team.

I didn't mention on the original post, but this actually happens to mslugx and tmnt2, so it is not related exclusively to Neo Geo. But your suggestion to disable the auto load is very welcome.
I hope fbalpha becomes the default core for arcade roms in later versions. For me it just seems to run better on this device.

**Comment by Olywa** [comment] 2022-06-14 02:28
Hi there, they are two very different issues, at least in the cause, I assure you :)

I'm glad to hear that disabling auto-load is of some help. Unfortunately FBA won't replace Mame as the default since Mame just supports far more games than FBA can but I do agree that FBA (and FBA2012 actually) are great cores, which is why they are included as alternatives ;)

If you are satisfied with the workaround and there is nothing else pertaining to this particular issue can I ask you to set the status to Closed please?

Many thanks.

**Closed** 2022-06-14 02:30 UTC
