### ISSUE TITLE
Airplane game can't spin

### ISSUE THREAD

**Issue by fengfrw** [jimgraygit/Onion#104] opened 2022-04-04 09:29 UTC
The plane game defaults to horizontal screen and cannot be rotated. Several versions of RA set the rotation option to be invalid. I hope it can be fixed, thank you!

**Comment by Olywa** [comment] 2022-04-04 18:59
@fengfrw There are a ton of airplane games on many systems mate, you might want to provide some specific game names but I think this may be a duplicate of issue #89 regarding vertical games being rotated & incorrectly displayed.

**Comment by fengfrw** [comment] 2022-04-05 02:32
First of all thanks for the answer. Basically, they are all ARCADE. For example, the tokio game cannot set Video Rotation when using FB Alpha.opt. When using Final Burn Neo.opt, Normal horizontal screen is displayed. Video Rotation selection of 90deg is invalid. 180deg and 270deg can be rotated, but vertical screen games cannot be played. Switching to mame2003 (or mame2003plus) can normally vertical screen (also can not set Rotation RA). Exactly the same as #89.

**Comment by Olywa** [comment] 2022-04-08 00:09
@fengfrw Cool - good info but I think this issue should be closed as you confirmed it's a duplicate of 89. The devs are certainly aware and it's looking like it will be addressed in an upcoming release very soon.

**Comment by Sichroteph** [comment] 2022-04-10 07:40
mama2003 plus is now the new default

**Closed by Sichroteph** 2022-04-10 07:40 UTC
