### ISSUE TITLE
Favorites with the same name

### ISSUE THREAD

**Issue by eloy83** [jimgraygit/Onion#209] opened 2022-05-13 20:50 UTC
Saving multiple favorites with the same name for different consoles leads to just one entry in favorites list.

**Comment by Wapp92** [comment] 2022-05-15 12:59
Duplicate of  #173

**Comment by Sichroteph** [comment] 2022-05-30 13:29
I contacted Miyoo about this today. Thanks for your feedback.

**Closed by Sichroteph** 2022-05-30 13:29 UTC
