### ISSUE TITLE
3.55 - Vertical Arcade games are rotated 90 degrees (sideways)

### ISSUE THREAD

**Issue by Olywa** [jimgraygit/Onion#89] opened 2022-03-27 05:24 UTC
Vertical games are displayed in the wrong orientation, rotated sideways by default to fill the screen. This makes them no longer playable. Some good examples are 1941 Counter Attack, Arkanoid, Bagman 2, Block Carnival. I have played with the various video options and cannot seem to find a way to make them appear correctly.

**Comment by IllustratedMan-code** [comment] 2022-04-02 16:59
Can confirm I have this issue with the ARCADE emulator. Digdug and Galaga both have the issue

**Comment by IllustratedMan-code** [comment] 2022-04-02 17:08
I have tried setting the output rotation, to no affect. The "vertical mode" setting doesn't seem to do anything either.

**Comment by Olywa** [comment] 2022-04-04 18:53
Issue persists in 3.55 (titles updated)

**Comment by DaPiMan** [comment] 2022-04-08 21:10
You can fix this per broken game as follows if using FinalBurn Neo:

Menu/select for the quick menu while in game with incorrect orientation. 

1. Options
2. Vertical Mode (toggle it on or toggle it off)
3. Manage core options 
4. "save game options" a game config is created for any options you change for this specific rom
5. b button x 2
6. Resume game 

Screen should have flipped correctly. I'm using Onion 3.55 and needed to do this for Q-Bert and by saving game options it only set the vertical setting change for this one game. Hope this helped. I also shared this on Retro Game Handhelds Discord channel. Cheers :)

**Comment by Olywa** [comment] 2022-04-09 00:42
@DaPiMan Thanks for the response. I'm familiar with these steps but unfortunately they don't seem to work with the default arcade core (fbalpha2012) and some games don't perform so well in FBNeo. There was talk on the discord of switching the default core Arcade core to Mame recently I think so that will also solve it (I'm currently using Mame for this reason).

**Comment by DaPiMan** [comment] 2022-04-09 15:03
I think the issue is video driver related: read here https://github.com/libretro/RetroArch/issues/7447

**Comment by DaPiMan** [comment] 2022-04-10 00:44
This is fixed with 3.6 as it's now using MAME 2003+ Core. Tested this morning. FBA can be used from Expert Menu as well if desired with FBALPHA rom folder.

**Closed** 2022-04-10 07:44 UTC
