### ISSUE TITLE
No restart of psx Games

### ISSUE THREAD

**Issue by El-Zocko** [jimgraygit/Onion#204] opened 2022-05-12 17:32 UTC
Everytime i will restart a psx Game the Miyoo will frozen. 3.9.1

**Comment by Olywa** [comment] 2022-05-13 09:19
Hi there, I have just tried this with a couple of PSX games and cannot reproduce the issue, it works fine here. 
I launch a PSX game, press Menu+Select to open Retroarch, navigate to 'restart' & press A. The game reboots as expected.

I assume these are the same steps you are taking. 
My roms are in .chd and .pbp formats - can you confirm the format of your roms?

It sounds like something may be wrong with your installation or configuration, a fresh, (re)install of Onion will likely resolve this.

**Comment by El-Zocko** [comment] 2022-05-13 10:40
Every Game is in .pbp Format. I have start a new online Installation but it dosn‘t work…

**Comment by Olywa** [comment] 2022-05-14 05:44
can you describe the exact steps that cause this to happen for you?
And is it only with PSX games and does not happen with other consoles/games?
Are you using the SD card that came with the mini (or a new card)?

There is a new Onion release today, I would also recommend to try the latest version.

**Comment by El-Zocko** [comment] 2022-05-15 07:01
First step— Select+Menu, next—restart: Game is frozen. No Chance to Play every time. I youse 3.8.2&3.9.2… the Same Problem. Today i Test the nee Beta.

**Comment by El-Zocko** [comment] 2022-05-15 17:46
Beta—> the Same issue 🤮

**Comment by Olywa** [comment] 2022-05-15 18:00
@El-Zocko Thanks for reporting back. It's difficult to know what's going on as I cannot replicate the problem on my device so it seems to be something unique to your set up. 

Can I suggest you join the discord channel. It's a very active & friendly community and we can try to help you work through it there. https://discord.com/channels/529983248114122762/891336865540620338

**Comment by Olywa** [comment] 2022-05-15 20:09
Hi @El-Zocko 
I was thinking some more about this, maybe you could try disabling the auto loading of save states in the the retroarch menu to see if the issue remains. Since I think you cannot get to the RA menus easily you should go into Apps and launch RA from there, then...

Load Core->Sony - PlayStation (PCSX ReArmed)
Setting->Saving->Load State Automatically (turn it off)
Will you need to save the configuration changes (Settings->Save Current Configuration).

**Comment by Sichroteph** [comment] 2022-05-23 20:34
I am guessing it is a rom issue. Also take in account that restating the game takes time and may appear frozen for a little while. Closing because it's an old version, don't hesitate to answer here if the issue persists.

**Closed by Sichroteph** 2022-05-23 20:34 UTC
