### ISSUE TITLE
OpenBOR fix needed

### ISSUE THREAD

**Issue by bubblegoosenipple** [jimgraygit/Onion#185] opened 2022-05-07 22:36 UTC
Can there be an update on what is causing OpenBOR to not work?  Thank you for working on this!

**Comment by rnzr** [comment] 2022-05-07 23:25
duplicate of #124

**Comment by dwmccoy** [comment] 2022-05-18 18:12
The following is a working solution for Onion OS 3.10.5. Please report if it works for you.

DO NOT Install OpenBOR from the Onion OS Installer as it is currently broken.

Download parasyte [https://github.com/steward-fu/miyoo-mini/releases/download/stock/parasyte_20220125.zip](https://github.com/jimgraygit/Onion/issues/url)
Download OpenBOR [https://github.com/steward-fu/miyoo-mini/releases/download/stock/openbor_20220422.zip](https://github.com/jimgraygit/Onion/issues/url)

Unzip parasyte and place the parasyte folder in /App folder on root of SDCARD
Unzip OpenBOR and place openbor folder in /EMU folder on root of SDCARD

Edit the config.json file located in /Emu/openbor to have following values

{
"label":"OpenBOR",
"icon":"icon.png",
"iconsel":"icon.png",
"launch":"launch.sh",
"rompath":"./Paks",
"imgpath":"./Imgs",
"useswap":1,
"shortname":0,
"hidebios":0,
"extlist":"pak|PAK"
}

Edit the launch.sh file located in /EMU/openbor to have following values

#!/bin/sh

killall audioserver
killall audioserver.mod

mydir=dirname "$0"
midir="/mnt/SDCARD/App/parasyte/rootfs"

export HOME=$mydir
export PATH=$mydir:$midir/usr/local/sbin:$midir/usr/local/bin:$midir/usr/sbin:$midir/usr/bin:$midir/sbin:$midir/bin:$PATH
export LD_LIBRARY_PATH=$mydir/lib:$midir/lib:$midir/usr/lib:$LD_LIBRARY_PATH
export SDL_VIDEODRIVER=mmiyoo
export SDL_AUDIODRIVER=mmiyoo
echo performance > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor

cd $mydir
./OpenBOR "$1"

/mnt/SDCARD/miyoo/app/audioserver &

Place all game pak files into the /EMU/openbor/Pak folder

Launch OpenBOR from the Consoles Menu ...... Enjoy

**Comment by Edwardphantom** [comment] 2022-05-18 22:51
testing ... first time ... long wait ....
LOADING screen appear to be stucked
pressed all keys nothing work yet .
popping sound start to repeat and going fast until an black screen
nothing more happens, mini is irresponsible now... 
restarted , same story
fresh install from SDcard

**Comment by dwmccoy** [comment] 2022-05-19 00:09
[OpenBOR Config Files.zip](https://github.com/jimgraygit/Onion/files/8721629/OpenBOR.Config.Files.zip)

I have attached my config.json and launch.sh files in the event something was copied wrong from my post.

**Comment by Edwardphantom** [comment] 2022-05-24 11:49
closing ticket, openBOr now running fine, some random closing in the selection pak screen, but i can deal with that, thanks a lot !

**Closed** 2022-05-29 07:29 UTC
